### ISSUE TITLE
MD5 Feedback

### ISSUE THREAD

**Issue by Samsterr** [Samsterr/SirSquirrelAssistant#42]
Do let me know feedback relating to MD5 such as troublesome packs, program behaviour and what not

**Comment by SupremacyOfTraps** [comment]
[squirrel.log](https://github.com/user-attachments/files/17991359/squirrel.log)
Well it just bugs out when trying to fuse the gifts

**Comment by Samsterr** [comment]
@SupremacyOfTraps i intend to rework fusion after thursdays update.

**Comment by SirKappa626** [comment]
not sure if youre doing specific packs based on team comp but getting warp as pack 5 as a bleed team just ends in a wipe almost everytime

**Comment by Samsterr** [comment]
@SirKappa626 you can just remove warp from your packlist. Exclusion per team will make it more messy but i might consider it due to sinking and kim

**Comment by iksghm** [comment]
I was wondering if it would be feasible for the script to detect the route with the most event nodes/least combat nodes to take 
I guess detecting which nodes connect to which could be annoying, so at least a way for the script to always prioritize event nodes when it comes across them would be great because especially in F4 and 5 taking just a couple of event nodes could decrease the clear time by 10+ minutes  
This would also make it so that it avoids the lengthy elite nodes and abno encounter nodes like the skin prophet that takes like 12 turns (more if you don't have an endgame team) to clear by win rating

**Comment by Samsterr** [comment]
@iksghm i am looking into this, the issue is that even though the nodes look the same to us. In the game there are slightly parallax shifts which the bot cant detect. My initial testing leaves me with about 3 pictures for every node which is not good. Skin prophet is already excluded by default since he only shows up on the wrath pack if im not mistakened

**Comment by DarkYato** [comment]
Assistant has been running pretty smooth for me since yesterday's update

**Comment by SteamPunkTeacup** [comment]
Not an issue or a suggestion but I just wanted to say the bot is phenomenal and the quick updates and bug fixes are amazing, thanks for making such a useful tool for people with not enough time. You're a champ

**Comment by Viavia46** [comment]
Would it be possible to have an option of running Sir Squirrel on the 2nd monitor? I tried swapping the HDMI ports and changed the primary monitor but the game still only gets detected on the same monitor as it did originally and idk why.

**Comment by Samsterr** [comment]
Refer to issue #44. Its not really something i can fix.

**Comment by Viavia46** [comment]
Ah, dang. I'm just very confused as to what is recognized as a primary monitor

**Comment by Samsterr** [comment]
@Viavia46 primary monitor should be the one with the taskbar. There should be a setting in windows to make a specific display your main one

**Comment by Viavia46** [comment]
Yeah, that somehow didn't change which monitor it detected the game on so I'm out of ideas. It's not a huge deal though.

**Comment by SoliDeoGloria000** [comment]
It stops when its collecting a reward after a battle. I have my status config with only sinking in it. 

2024-12-30 04:46:38,408 - src.core - INFO - Starting Battle
2024-12-30 04:46:39,139 - src.core - DEBUG - HOPELESS FOUND
2024-12-30 04:46:39,338 - src.core - DEBUG - []
2024-12-30 04:46:39,338 - src.core - DEBUG - BAD CLASHES FOUND
2024-12-30 04:47:17,574 - src.core - DEBUG - HOPELESS FOUND
2024-12-30 04:47:17,771 - src.core - DEBUG - []
2024-12-30 04:47:17,771 - src.core - DEBUG - BAD CLASHES FOUND
2024-12-30 04:47:22,500 - src.core - DEBUG - HOPELESS FOUND
2024-12-30 04:47:22,708 - src.core - DEBUG - []
2024-12-30 04:47:22,708 - src.core - DEBUG - BAD CLASHES FOUND
2024-12-30 04:47:41,230 - src.core - DEBUG - HOPELESS FOUND
2024-12-30 04:47:41,434 - src.core - DEBUG - []
2024-12-30 04:47:41,434 - src.core - DEBUG - BAD CLASHES FOUND
2024-12-30 04:47:55,096 - src.core - INFO - Loading
2024-12-30 04:47:59,454 - src.mirror - INFO - Reward Selection
2024-12-30 04:47:59,551 - src.mirror - INFO - Reward Selection: Status not found

And I was also having the problem of it not restarting a mirror dungeon run. 
2024-12-29 04:44:13,890 - src.mirror - DEBUG - Restshop: Refreshing Shop
2024-12-29 04:44:14,123 - src.mirror - DEBUG - Restshop: Found Keywordless Gifts
2024-12-29 04:44:14,243 - src.mirror - DEBUG - [(np.int64(1201), np.int64(406)), (np.int64(1431), np.int64(406))]
2024-12-29 04:44:14,243 - src.mirror - DEBUG - [(np.int64(1201), np.int64(406)), (np.int64(1431), np.int64(406))]
2024-12-29 04:44:14,263 - src.mirror - DEBUG - 1.3333333333333333
2024-12-29 04:44:14,323 - src.mirror - DEBUG - 1.3333333333333333
2024-12-29 04:44:16,997 - src.mirror - INFO - Navigating
2024-12-29 04:44:21,622 - src.mirror - INFO - Selecting Squad for Battle
2024-12-29 04:44:30,994 - src.core - INFO - Starting Battle
2024-12-29 04:46:00,946 - src.core - INFO - Loading
2024-12-29 04:46:05,049 - src.mirror - INFO - Navigating
2024-12-29 04:46:05,795 - src.mirror - DEBUG - []
2024-12-29 04:46:05,795 - src.mirror - DEBUG - []
2024-12-29 04:46:05,795 - src.mirror - DEBUG - set()
2024-12-29 04:46:05,795 - src.mirror - DEBUG - [(1080, 197), (1080, 517), (1080, 836)]
2024-12-29 04:46:05,795 - src.mirror - DEBUG - [(1080, 197), (1080, 517), (1080, 836)]

I want to mention the mirror dungeon bot was working fairly well before the event update, its after I got the event collection reward screen after a run and the bot couldn't continue I had to update. I was on 1.0.3.1. I would just have the occasional lock on collecting reward after battle. Thanks for the bot.

**Comment by Samsterr** [comment]
@SoliDeoGloria000 i did not change anythting relating to reward selection since 1.0.3.1 and the second issue stated has already been fixed in the latest hotfix.

**Comment by mitoux** [comment]
Stops When Fusing

2024-12-31 22:38:29,121 - src.mirror - DEBUG - []
2024-12-31 22:38:29,121 - src.mirror - DEBUG - set()
2024-12-31 22:38:29,121 - src.mirror - DEBUG - [(1080, 197), (1080, 517), (1080, 836)]
2024-12-31 22:38:29,122 - src.mirror - DEBUG - [(1080, 197), (1080, 517), (1080, 836)]
2024-12-31 22:38:32,580 - src.mirror - INFO - Restshop
2024-12-31 22:38:32,580 - src.mirror - INFO - Starting Fusion
2024-12-31 22:38:34,872 - __main__ - ERROR - Template image 'None' not found.

It just stops at the "Keyword you want to fuse into" page.

**Comment by SoliDeoGloria000** [comment]
@Samsterr  I'm saying this problem was still happening during 1.0.3.1, but it feels more exacerbated by the bot not restarting and it stopping on this selection screen. I will download the latest hotfix. Happy New Year!
![Screenshot (290)](https://github.com/user-attachments/assets/d09c56aa-e760-4a2f-92ec-af7424c2be97)

**Comment by Samsterr** [comment]
@SoliDeoGloria000 does it consistently happen on this screen or only sometimes? i have checked and there's no issue with detection 
![{83EA936D-FEDF-42B2-A8EB-1F42DA8064B6}](https://github.com/user-attachments/assets/1835da2b-a96d-4eb8-b1fd-5ae0249ae593)

**Comment by SoliDeoGloria000** [comment]
@Samsterr Only sometimes on this screen the last time it happen was on this ego gift, but usually it can run through a couple of floors then bug out after a random stage that gives a ego gift to collect. 
![image](https://github.com/user-attachments/assets/eb2c1be3-9a60-474c-bd1b-78e7dc4530cd)

**Comment by Samsterr** [comment]
@SoliDeoGloria000 ok do let me know if it happens again. As of now i think it might be a timing issue as the logs are inline with what is expected

**Comment by Sannann** [comment]
Incredibly minor nitpick, but when you enter the MD menu for the first time (From the Drive area in main menu), it takes a bit longer to load and bricks the bot. A tiny delay would fix it I think.

**Comment by Sannann** [comment]
Sometimes you get EGO gifts after battles, before the actual three reward selection, and the bot doesnt seem to be able to handle this or doesnt wait long enough:

2025-01-03 12:35:42,377 - src.mirror - INFO - Navigating
2025-01-03 12:35:46,735 - src.mirror - INFO - Selecting Squad for Battle
2025-01-03 12:35:56,388 - src.core - INFO - Starting Battle
2025-01-03 12:38:10,218 - src.core - INFO - Loading
2025-01-03 12:38:14,726 - src.mirror - INFO - Encounter Reward Selection
2025-01-03 12:38:22,455 - src.mirror - INFO - Encounter Reward Selection
2025-01-03 12:38:27,649 - src.mirror - INFO - Encounter Reward Selection
2025-01-03 12:38:32,784 - src.mirror - INFO - Encounter Reward Selection
2025-01-03 12:38:37,964 - src.mirror - INFO - Encounter Reward Selection
2025-01-03 12:38:43,143 - src.mirror - INFO - Encounter Reward Selection
2025-01-03 12:38:48,262 - src.mirror - INFO - Encounter Reward Selection...

**Comment by Samsterr** [comment]
@Sannann what do you mean by a chance to get ego gift? Like the example page the other user further up posted or the ego gift get prompt.

**Comment by Sannann** [comment]
I will send a screenshot if it happens again, but just visualize the ego gift receival/accept prompt. After fights I believe there is a random chance to get a free ego gift, as soon as the fight ends you just get it and you need to click confirm to proceed with the normal rewards/gameplay, but the bot isnt ready for this so it bricks. For example, last time, I finished a boss node, got such an ego gift, and the bot (as can be seen in the log) kept looking for the standard reward selection, never being able to find it because it needed to detect and accept the bonus ego gift before the reward selection

**Comment by Samsterr** [comment]
@Sannann that doesnt answer the question of which prompt is it because they are both acceptence of an ego gift. Also by boss node do you mean the final node of the floor or an abnormality encounter.

**Comment by Sannann** [comment]
![image](https://github.com/user-attachments/assets/0fb2c438-596a-42ce-aaf9-814fcf8d13ae)
I think this is similar or the same scenario as last time. I get an ego gift before reward selection and the bot bricks. Is this enough?
Log:
2025-01-04 09:33:01,600 - src.mirror - INFO - Navigating
2025-01-04 09:33:08,279 - src.mirror - INFO - Selecting Squad for Battle
2025-01-04 09:33:18,575 - src.core - INFO - Starting Battle
2025-01-04 09:34:16,148 - src.core - INFO - Loading
2025-01-04 09:34:20,659 - src.mirror - INFO - Encounter Reward Selection
2025-01-04 09:34:28,612 - src.mirror - INFO - Encounter Reward Selection
2025-01-04 09:34:33,759 - src.mirror - INFO - Encounter Reward Selection...

**Comment by Samsterr** [comment]
@Sannann prioritised as of latest update
